# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_message.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'device_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65vice_message.proto\x12\x06\x64\x65vice\"\xa5\x01\n\rDeviceReading\x12\x14\n\x0c\x61rrival_time\x18\x01 \x01(\x03\x12\x15\n\rcreation_time\x18\x02 \x01(\x03\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\x05\x12\r\n\x05model\x18\x05 \x01(\t\x12\x0c\n\x04user\x18\x06 \x01(\t\x12\n\n\x02gt\x18\x07 \x01(\t\x12\t\n\x01x\x18\x08 \x01(\x01\x12\t\n\x01y\x18\t \x01(\x01\x12\t\n\x01z\x18\n \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEREADING']._serialized_start=33
  _globals['_DEVICEREADING']._serialized_end=198
# @@protoc_insertion_point(module_scope)
