FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install numpy

# Copy our code
COPY device_consumer.py .

CMD ["python", "device_consumer.py"]